class Data:
    def __init__(self):
        self.ak15_regressed_mass = []
        self.truth = []
        self.lep1_pt = []
        self.lep1_eta = []
        self.lep1_phi = []
        self.lep1_mass = []
        self.lep2_pt = []
        self.lep2_eta = []
        self.lep2_phi = []
        self.lep2_mass = []
        self.ak15_pt = []
        self.ak15_eta = []
        self.ak15_phi = []
        self.ak15_deltaR_sj12 = []
        self.ak15_sj1_pt = []
        self.ak15_sj2_pt = [] 